// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcxyrthrzviksmksfvmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjeHlydGhyenZpa3Nta3Nmdm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjgyODUsImV4cCI6MjA2MDIwNDI4NX0.LWnJZc-c1NJxQfnThxN61YMuMWks8luvpJsd5ShhCus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);